### ISSUE TITLE
Fail fast if out folder points to an empty directory

### ISSUE THREAD

**Issue by bsideup** [spring-io/artifactory-resource#34]
If user misconfigures their pipeline, the plugin should fail fast and instead of returning "No artifacts found to deploy" could point to the fact that the `folder` parameter is either a file or a missing directory.

**Comment by philwebb** [comment]
We already have [these checks](https://github.com/spring-io/artifactory-resource/blob/a70797b18cd8a36f847049bdbb085222b7951cbc/src/main/java/io/spring/concourse/artifactoryresource/io/Directory.java#L43-L45) but in your case the folder did exist because [it was specified as an output](https://github.com/reactor/BlockHound/blob/aea046f65c17da3cdecd178604a634bc63e6dcd3/pipeline.yml#L44).

**Comment by philwebb** [comment]
I think's worth us adding a specific failure if the folder is entirely empty when we try to scan it. That's most probably a configuration error.
